# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/e/Universidad/Master/PACS/PACS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/e/Universidad/Master/PACS/PACS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/e/Universidad/Master/PACS/PACS/CMakeFiles /mnt/e/Universidad/Master/PACS/PACS/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/e/Universidad/Master/PACS/PACS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hello

# Build rule for target.
hello: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello
.PHONY : hello

# fast build rule for target.
hello/fast:
	$(MAKE) -f code_examples/CMakeFiles/hello.dir/build.make code_examples/CMakeFiles/hello.dir/build
.PHONY : hello/fast

#=============================================================================
# Target rules for targets named saxpy_future

# Build rule for target.
saxpy_future: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 saxpy_future
.PHONY : saxpy_future

# fast build rule for target.
saxpy_future/fast:
	$(MAKE) -f code_examples/CMakeFiles/saxpy_future.dir/build.make code_examples/CMakeFiles/saxpy_future.dir/build
.PHONY : saxpy_future/fast

#=============================================================================
# Target rules for targets named thread_joinable

# Build rule for target.
thread_joinable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thread_joinable
.PHONY : thread_joinable

# fast build rule for target.
thread_joinable/fast:
	$(MAKE) -f code_examples/CMakeFiles/thread_joinable.dir/build.make code_examples/CMakeFiles/thread_joinable.dir/build
.PHONY : thread_joinable/fast

#=============================================================================
# Target rules for targets named saxpy

# Build rule for target.
saxpy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 saxpy
.PHONY : saxpy

# fast build rule for target.
saxpy/fast:
	$(MAKE) -f code_examples/CMakeFiles/saxpy.dir/build.make code_examples/CMakeFiles/saxpy.dir/build
.PHONY : saxpy/fast

#=============================================================================
# Target rules for targets named hello_pacs_two_threads

# Build rule for target.
hello_pacs_two_threads: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello_pacs_two_threads
.PHONY : hello_pacs_two_threads

# fast build rule for target.
hello_pacs_two_threads/fast:
	$(MAKE) -f code_examples/CMakeFiles/hello_pacs_two_threads.dir/build.make code_examples/CMakeFiles/hello_pacs_two_threads.dir/build
.PHONY : hello_pacs_two_threads/fast

#=============================================================================
# Target rules for targets named lambda_example

# Build rule for target.
lambda_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lambda_example
.PHONY : lambda_example

# fast build rule for target.
lambda_example/fast:
	$(MAKE) -f code_examples/CMakeFiles/lambda_example.dir/build.make code_examples/CMakeFiles/lambda_example.dir/build
.PHONY : lambda_example/fast

#=============================================================================
# Target rules for targets named saxpy_scaling

# Build rule for target.
saxpy_scaling: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 saxpy_scaling
.PHONY : saxpy_scaling

# fast build rule for target.
saxpy_scaling/fast:
	$(MAKE) -f code_examples/CMakeFiles/saxpy_scaling.dir/build.make code_examples/CMakeFiles/saxpy_scaling.dir/build
.PHONY : saxpy_scaling/fast

#=============================================================================
# Target rules for targets named synchronization

# Build rule for target.
synchronization: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 synchronization
.PHONY : synchronization

# fast build rule for target.
synchronization/fast:
	$(MAKE) -f code_examples/CMakeFiles/synchronization.dir/build.make code_examples/CMakeFiles/synchronization.dir/build
.PHONY : synchronization/fast

#=============================================================================
# Target rules for targets named parallel_sum_future

# Build rule for target.
parallel_sum_future: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parallel_sum_future
.PHONY : parallel_sum_future

# fast build rule for target.
parallel_sum_future/fast:
	$(MAKE) -f code_examples/CMakeFiles/parallel_sum_future.dir/build.make code_examples/CMakeFiles/parallel_sum_future.dir/build
.PHONY : parallel_sum_future/fast

#=============================================================================
# Target rules for targets named packaged_task

# Build rule for target.
packaged_task: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 packaged_task
.PHONY : packaged_task

# fast build rule for target.
packaged_task/fast:
	$(MAKE) -f code_examples/CMakeFiles/packaged_task.dir/build.make code_examples/CMakeFiles/packaged_task.dir/build
.PHONY : packaged_task/fast

#=============================================================================
# Target rules for targets named hello_pacs_args

# Build rule for target.
hello_pacs_args: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello_pacs_args
.PHONY : hello_pacs_args

# fast build rule for target.
hello_pacs_args/fast:
	$(MAKE) -f code_examples/CMakeFiles/hello_pacs_args.dir/build.make code_examples/CMakeFiles/hello_pacs_args.dir/build
.PHONY : hello_pacs_args/fast

#=============================================================================
# Target rules for targets named mutex

# Build rule for target.
mutex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mutex
.PHONY : mutex

# fast build rule for target.
mutex/fast:
	$(MAKE) -f code_examples/CMakeFiles/mutex.dir/build.make code_examples/CMakeFiles/mutex.dir/build
.PHONY : mutex/fast

#=============================================================================
# Target rules for targets named atomic_synchronization

# Build rule for target.
atomic_synchronization: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 atomic_synchronization
.PHONY : atomic_synchronization

# fast build rule for target.
atomic_synchronization/fast:
	$(MAKE) -f code_examples/CMakeFiles/atomic_synchronization.dir/build.make code_examples/CMakeFiles/atomic_synchronization.dir/build
.PHONY : atomic_synchronization/fast

#=============================================================================
# Target rules for targets named pi_taylor_parallel_kahan

# Build rule for target.
pi_taylor_parallel_kahan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pi_taylor_parallel_kahan
.PHONY : pi_taylor_parallel_kahan

# fast build rule for target.
pi_taylor_parallel_kahan/fast:
	$(MAKE) -f Laboratory-3/CMakeFiles/pi_taylor_parallel_kahan.dir/build.make Laboratory-3/CMakeFiles/pi_taylor_parallel_kahan.dir/build
.PHONY : pi_taylor_parallel_kahan/fast

#=============================================================================
# Target rules for targets named pi_taylor_parallel

# Build rule for target.
pi_taylor_parallel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pi_taylor_parallel
.PHONY : pi_taylor_parallel

# fast build rule for target.
pi_taylor_parallel/fast:
	$(MAKE) -f Laboratory-3/CMakeFiles/pi_taylor_parallel.dir/build.make Laboratory-3/CMakeFiles/pi_taylor_parallel.dir/build
.PHONY : pi_taylor_parallel/fast

#=============================================================================
# Target rules for targets named pi_taylor_sequential

# Build rule for target.
pi_taylor_sequential: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pi_taylor_sequential
.PHONY : pi_taylor_sequential

# fast build rule for target.
pi_taylor_sequential/fast:
	$(MAKE) -f Laboratory-3/CMakeFiles/pi_taylor_sequential.dir/build.make Laboratory-3/CMakeFiles/pi_taylor_sequential.dir/build
.PHONY : pi_taylor_sequential/fast

#=============================================================================
# Target rules for targets named smallpt_thread_pool

# Build rule for target.
smallpt_thread_pool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smallpt_thread_pool
.PHONY : smallpt_thread_pool

# fast build rule for target.
smallpt_thread_pool/fast:
	$(MAKE) -f Laboratory-4/CMakeFiles/smallpt_thread_pool.dir/build.make Laboratory-4/CMakeFiles/smallpt_thread_pool.dir/build
.PHONY : smallpt_thread_pool/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... hello"
	@echo "... saxpy_future"
	@echo "... thread_joinable"
	@echo "... saxpy"
	@echo "... hello_pacs_two_threads"
	@echo "... lambda_example"
	@echo "... saxpy_scaling"
	@echo "... synchronization"
	@echo "... parallel_sum_future"
	@echo "... packaged_task"
	@echo "... hello_pacs_args"
	@echo "... mutex"
	@echo "... atomic_synchronization"
	@echo "... pi_taylor_parallel_kahan"
	@echo "... pi_taylor_parallel"
	@echo "... pi_taylor_sequential"
	@echo "... smallpt_thread_pool"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

